package com.dianping.puma.core.util.sql;

public enum DDLType {

	ALTER_DATABASE,
	ALTER_EVENT,
	ALTER_LOGFILE_GROUP,
	ALTER_FUNCTION,
	ALTER_PROCEDURE,
	ALTER_SERVER,
	ALTER_TABLE,
	ALTER_TABLESPACE,
	ALTER_VIEW,

	CREATE_DATABASE,
	CREATE_EVENT,
	CREATE_INDEX,
	CREATE_LOGFILE_GROUP,
	CREATE_FUNCTION,
	CREATE_PROCEDURE,
	CREATE_SERVER,
	CREATE_TABLE,
	CREATE_TABLESPACE,
	CREATE_TRIGGER,
	CREATE_VIEW,

	DROP_DATABASE,
	DROP_EVENT,
	DROP_INDEX,
	DROP_LOGFILE_GROUP,
	DROP_FUNCTION,
	DROP_SERVER,
	DROP_TABLE,
	DROP_TABLESPACE,
	DROP_TRIGGER,
	DROP_VIEW,

	RENAME_DATABASE,
	RENAME_TABLE,

	TRUNCATE_TABLE,
}
